title: Wang Tao's Homepage
page-top-title: Wang Tao
top-section-bg-text: Central China Normal University
home-subtitle: Wang Tao&ensp;|&ensp;王涛
copyright-text: '&copy; Wang Tao 2023-2026. All Rights Reserved.'
